# Generated by Django 5.2.13 on 2026-04-13 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Streamer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('avatar', models.CharField(default='🎮', max_length=10)),
                ('main_pos', models.CharField(max_length=20)),
                ('main_tier', models.CharField(max_length=10)),
                ('main_most', models.JSONField(default=list)),
                ('sub_pos', models.CharField(max_length=20)),
                ('sub_tier', models.CharField(max_length=10)),
                ('sub_most', models.JSONField(default=list)),
                ('note', models.TextField(blank=True, default='')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
