# Generated by Django 5.2.13 on 2026-04-13 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overwatch', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='streamer',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='streamer',
            name='order',
        ),
        migrations.AlterField(
            model_name='streamer',
            name='sub_pos',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='streamer',
            name='sub_tier',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
